name: alatpay_sdk
description: >
  A Flutter SDK for seamless integration with Alat Pay, enabling secure, fast, and reliable in-app payments.
  It provides an easy payment initialization, confirmation, transaction tracking, and UI Customization,
  allowing developers to accept payments effortlessly within their Flutter apps.

version: 1.0.3

homepage: https://github.com/ALATPay/alatpay-flutter
repository: https://github.com/ALATPay/alatpay-flutter
issue_tracker: https://github.com/ALATPay/alatpay-flutter/issues
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI and network libraries
  cupertino_icons: ^1.0.8
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/banks/